#!/usr/bin/env bash

function die () {
    echo "Fatal Error: $1"
    exit 1
}

if [ `uname` = 'Darwin' ]; then
    md5="md5 -q"
elif [ `uname` = 'Linux' ]; then 
    md5=md5sum
else
    die  "Unknown system: $(uname)"
fi

GDRIVE=`which gdrive`

DRIVE_ROOT_DIRECTORY=0B48GsO9wiGeROFFXdFlxeWw5TXc
STAGING_AREA=./.freezer_staging

if [ ".$1" = "." ]; then
   die "Missing victim"
fi
	
victim=$1

test -e $i || die "$victim doesn't exist"
test -d $i || die "We can only archive directories"

victim=$(echo $victim |perl -ne 's/\/$//g;print')
echo $victim
mkdir -p $STAGING_AREA

archive_file=$RANDOM.tbz
archive=./.freezer_staging/$archive_file

tar -p -v -c -j -f  $archive $victim  2> $archive.manifest || die "Creating tar ball"

$md5 $archive | cut -f  1 -d " " > $archive.md5sum

$GDRIVE upload --parent $DRIVE_ROOT_DIRECTORY $archive --name $victim.tbz || die "Uploading archive"
$GDRIVE upload --parent $DRIVE_ROOT_DIRECTORY $archive.md5sum --name $victim.md5sum.txt || die "Uploading md5sum"
$GDRIVE upload --parent $DRIVE_ROOT_DIRECTORY $archive.manifest --name $victim.manifest.txt || die "Uploading manifest"

#echo $GDRIVE list --query "'$DRIVE_ROOT_DIRECTORY' in parents and name = '$victim.tbz' and trashed = false" \| tail -1\| cut -f 1 -d ' '
archive_id=$($GDRIVE list --query "'$DRIVE_ROOT_DIRECTORY' in parents and name = '$victim.tbz' and trashed = false" | tail -1 | cut -f 1 -d ' ')

#echo $GDRIVE info $archive_id \| grep Md5sum \|cut -f 2 -d ' '
remote_md5=$($GDRIVE info $archive_id | grep Md5sum |cut -f 2 -d ' ')

echo $remote_md5 != $(cat $archive.md5sum)

if [ $remote_md5 != $(cat $archive.md5sum) ]; then
    die "Checksums don't match"
fi

#rm -rf $victim
rm -rf $STAGING_AREA
